baseurl: https://ctrl-alt.fail
languageCode: en-gb
theme: hugo-theme-stack
paginate: 5
title: ctrl-alt-fail

languages:
    en:
        languageName: English
        title: ctrl-alt-fail
        weight: 1

DefaultContentLanguage: en

hasCJKLanguage: false

permalinks:
    post: /:slug/
    page: /:slug/

params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true
    favicon:

    footer:
        since: 2025
        customText:

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 MST

    sidebar:
        emoji: 🧙🏻‍♂️
        subtitle: Decoding life one byte at a time.
        avatar:
            enabled: true
            local: true
            src: img/avatar.png

    article:
        math: false
        toc: true
        readingTime: true
        license:
            enabled: true
            default: Licensed under CC BY-NC-SA 4.0

    comments:
        enabled: false

    widgets:
        homepage:
            - type: search
            - type: archives
              params:
                  limit: 5
            - type: categories
              params:
                  limit: 10
            - type: tag-cloud
              params:
                  limit: 10
        page:
            - type: toc

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src:

    colorScheme:
        toggle: false
        default: dark

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

### Custom menu
### See https://docs.stack.jimmycai.com/configuration/custom-menu.html
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter
menu:
    main: []

    social:
        - identifier: github
          name: GitHub
          url: https://github.com/ctrl-alt-fail
          params:
              icon: brand-github

        - identifier: linkedin
          name: Linkedin
          url: https://linkedin.com/in/josephsfleet/
          params:
              icon: brand-linkedin

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    goldmark:
        renderer:
            unsafe: false
    tableOfContents:
        endLevel: 4
        ordered: true
        startLevel: 2
    highlight:
        noClasses: false
        codeFences: true
        guessSyntax: true
        lineNoStart: 1
        lineNos: true
        lineNumbersInTable: true
        tabWidth: 4